# Generated by Django 4.1.5 on 2023-01-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(help_text='Limite de 50 characteres.', max_length=50)),
                ('password', models.CharField(help_text='Limite de 50 characteres.', max_length=50, verbose_name='senha')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.account', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
            },
        ),
    ]
